"""Model Card generation in Google / Hugging Face style.

Produces a human-readable Markdown card and a structured JSON
counterpart from the artifacts of a single audit run. Designed to
be safe in the face of partially-populated input dicts so it can be
called both from the analyze pipeline and ad-hoc on historical runs.
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any, Dict


def _fmt_int(value: Any) -> str:
    try:
        return f"{int(value):,}"
    except (TypeError, ValueError):
        return str(value) if value is not None else "N/A"


def _fmt_metric(value: Any) -> str:
    if value is None:
        return "N/A"
    try:
        return f"{float(value):.3f}"
    except (TypeError, ValueError):
        return str(value)


def _safe_float(value: Any, default: float = 0.0) -> float:
    try:
        return float(value)
    except (TypeError, ValueError):
        return default


def generate_model_card(
    run_data: Dict[str, Any],
    user: Dict[str, Any],
    use_case: str,
) -> Dict[str, Any]:
    """Build markdown + structured JSON model card for an audit run."""
    bias_results: Dict[str, Any] = run_data.get("bias_results", {}) or {}
    auto_detected: Dict[str, Any] = run_data.get("auto_detection", {}) or {}
    summary: Dict[str, Any] = run_data.get("dataset_summary", {}) or {}
    compliance: Dict[str, Any] = run_data.get("compliance_report", {}) or {}
    risk_score = _safe_float(run_data.get("overall_risk_score"), 0.0)
    today = datetime.now(timezone.utc)

    fairness_rows = []
    for attr, res in bias_results.items():
        if not isinstance(res, dict):
            continue
        di = _fmt_metric(res.get("disparate_impact"))
        spd = _fmt_metric(res.get("statistical_parity_difference"))
        passes = "PASS" if res.get("passes_80_percent_rule") else "FAIL"
        sev = str(res.get("severity", "unknown")).upper()
        fairness_rows.append(f"| {attr} | {di} | {spd} | {passes} | {sev} |")

    recs = []
    for attr, res in bias_results.items():
        if not isinstance(res, dict):
            continue
        if not res.get("passes_80_percent_rule"):
            recs.append(
                f"- **{attr}**: Disparate impact "
                f"({_fmt_metric(res.get('disparate_impact'))}) is below the 0.80 "
                "threshold. Consider re-weighting or resampling."
            )
    if risk_score > 0.7:
        recs.append(
            "- **High overall risk**: Immediate remediation recommended before "
            "deployment."
        )
    if not recs:
        recs.append(
            "- No critical issues detected. Continue monitoring in production."
        )

    comp_rows = []
    for _reg_id, comp in compliance.items():
        if not isinstance(comp, dict):
            continue
        status_value = comp.get("overall_status", "MANUAL_REVIEW")
        comp_rows.append(
            f"| {comp.get('regulation', '')} | {comp.get('jurisdiction', '')} | "
            f"{status_value} |"
        )

    protected_attrs = auto_detected.get("protected_attrs", []) or []
    protected_rendered = (
        ", ".join(f"`{a}`" for a in protected_attrs) if protected_attrs else "N/A"
    )

    fairness_table = (
        "\n".join(fairness_rows)
        if fairness_rows
        else "| No results | - | - | - | - |"
    )
    compliance_table = (
        "\n".join(comp_rows)
        if comp_rows
        else "| No compliance check run | - | - |"
    )
    recommendations_block = "\n".join(recs)

    markdown = f"""# Model card: {use_case.title()} Decision Model

> Auto-generated by FairAudit on {today.strftime("%Y-%m-%d")}

## Model details
- **Use case**: {use_case}
- **Audit run ID**: {run_data.get("run_id", "N/A")}
- **Audited by**: {user.get("full_name", "Unknown")} ({user.get("email", "")})
- **Date**: {today.strftime("%Y-%m-%d")}
- **Overall risk score**: {risk_score:.2f} / 1.00

## Dataset summary
- **Rows analyzed**: {_fmt_int(summary.get("row_count"))}
- **Columns**: {_fmt_int(summary.get("column_count"))}
- **Label column** (auto-detected): `{auto_detected.get("label_col", "N/A")}`
- **Protected attributes** (auto-detected): {protected_rendered}
- **Dataset quality score**: {_fmt_metric(summary.get("dataset_quality_score"))}

## Fairness evaluation
| Attribute | Disparate Impact | Stat. Parity Diff | 80% Rule | Severity |
|-----------|-----------------|-------------------|----------|----------|
{fairness_table}

## Compliance status
| Regulation | Jurisdiction | Status |
|------------|-------------|--------|
{compliance_table}

## Recommendations
{recommendations_block}

## Caveats and limitations
- This audit covers statistical fairness metrics only. Causal discrimination may
  require additional investigation.
- Auto-detection of protected attributes may miss domain-specific proxies.
- Fairness metrics can be in tension with each other - optimizing one may worsen another.
- This card was auto-generated and should be reviewed by a qualified fairness auditor
  before relying on it for legal compliance decisions.

## Citation
If you use this audit in research or reporting, please cite:
> FairAudit Bias Detection Platform, run ID: {run_data.get("run_id", "N/A")},
> {today.strftime("%Y-%m-%d")}
"""

    return {
        "markdown": markdown,
        "json": {
            "model_details": {
                "use_case": use_case,
                "audit_date": today.isoformat(),
                "run_id": run_data.get("run_id"),
            },
            "fairness_metrics": bias_results,
            "compliance": compliance,
            "overall_risk_score": risk_score,
            "recommendations": recs,
        },
    }
